// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlx83UqsDM1L4Co8upLmEPpeZZmsxg4ak',
    appId: '1:755888158000:web:104a22bb54b0f3fcda84f5',
    messagingSenderId: '755888158000',
    projectId: 'household-account-book-project',
    authDomain: 'household-account-book-project.firebaseapp.com',
    storageBucket: 'household-account-book-project.appspot.com',
    measurementId: 'G-RRJFXC156P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcbpYfBgcHgS5EDsBaGh7MWI6ugROnM8',
    appId: '1:755888158000:android:4aa2ac15f7a8ed28da84f5',
    messagingSenderId: '755888158000',
    projectId: 'household-account-book-project',
    storageBucket: 'household-account-book-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDGkbBkdXcAHzvoY8WlN4l1jQtZyV6IME',
    appId: '1:755888158000:ios:76b749750836f85ada84f5',
    messagingSenderId: '755888158000',
    projectId: 'household-account-book-project',
    storageBucket: 'household-account-book-project.appspot.com',
    iosBundleId: 'com.example.householdAccountBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDGkbBkdXcAHzvoY8WlN4l1jQtZyV6IME',
    appId: '1:755888158000:ios:76b749750836f85ada84f5',
    messagingSenderId: '755888158000',
    projectId: 'household-account-book-project',
    storageBucket: 'household-account-book-project.appspot.com',
    iosBundleId: 'com.example.householdAccountBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlx83UqsDM1L4Co8upLmEPpeZZmsxg4ak',
    appId: '1:755888158000:web:31f71680ac8a442fda84f5',
    messagingSenderId: '755888158000',
    projectId: 'household-account-book-project',
    authDomain: 'household-account-book-project.firebaseapp.com',
    storageBucket: 'household-account-book-project.appspot.com',
    measurementId: 'G-0ZTC96GGBY',
  );
}
